name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  ghcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Update Version
      run: poetry version ${{github.event.release.tag_name}}
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/virtool/build-index
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
